version: '3.7'
services:
  web:
    container_name: chialisp-web
    build: .
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - mode: host
        target: 3000
        published: 3000
