version: '3.7'
services:
  web:
    container_name: chialisp-web
    build: .
    volumes:
      - ./docs:/usr/src/app/docs:cached
      - ./src:/usr/src/app/src:cached
      - ./static:/usr/src/app/static:cached
    ports:
      - mode: host
        target: 3000
        published: 3000
