apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chialisp-web-star
  namespace: chialisp-web
  labels:
    app: chialisp-web
spec:
  secretName: chialisp-web-star-tls
  dnsNames:
    - "*.chialisp.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cf
